pincode: 110001                     # Enter the required pincode
age: 36                             # Enter your age
password:                           # Enter your password here
email_id: suman.14san@gmail.com     # Enter your email ID here
phone:                              # Enter your mobile number here

